### ISSUE TITLE
Extend incremental reparsing to all braced blocks

### ISSUE THREAD

**Issue by matklad** [matklad/libsyntax2#66]
The incremental reparsing model of libsyntax2 is curly-block based.

* in the parser, we make sure that, for any pair of `{` and `}`, there's a syntax node for which curlys are the first and the last child.
* this gives us corollary: if edit is inside a matching pair of braces, and the pair remains matching after the edit is applied, the effects of the edit are contained to a single block. 
* this gives a rise to incremental re parsing algorithm: find closest curly-block, verify its structure, reparse.

Currently only expr blocks and struct blocks participate in this algorithm, but it should be extended to any kind of braced block. Here's the relevant code:

https://github.com/matklad/libsyntax2/blob/4f647096665b2ca3725ba1f7415a21fbc46044bb/crates/libsyntax2/src/lib.rs#L145-L147

it should be extended to all braced blocks. The relevant tests are here:

https://github.com/matklad/libsyntax2/blob/4f647096665b2ca3725ba1f7415a21fbc46044bb/crates/libsyntax2/tests/test/main.rs#L42

It would be nice to use `proptest` or fuzzing to check incremental re parsing! (cc @killercup  on the last one). Here's the top-level repasing API:

https://github.com/matklad/libsyntax2/blob/4f647096665b2ca3725ba1f7415a21fbc46044bb/crates/libsyntax2/src/lib.rs#L81

**Comment by matklad** [comment]
Cool, if there's any question I can help with, don't hesitate to ask here, @darksv ! A good first start is perhaps to just add a single more block to the list of cases, for example, a `match_arm_list`.

**Comment by darksv** [comment]
Thank you. I have implemented reparsing for remaining blocks. Now I want to give `proptest` a go and add more tests.
